"use client";

import { useState } from "react";
import Link from "next/link";
import LanguageSwitcher, { type Lang } from "@/components/LanguageSwitcher";
import { languageHref } from "@/lib/site";

export type { Lang } from "@/components/LanguageSwitcher";
const sourceUrl = "https://raw.githubusercontent.com/yodaluca23/Fusion-AltStore/refs/heads/main/source.json";

const copy = {
  en: {
    eyebrow: "FUSION · INSTALLATION GUIDE", title: <>Install Fusion on iPhone<br />and Apple TV.</>, lead: "A complete step-by-step guide using AltStore Classic, AltServer, and Xcode.", releases: "Fusion Releases ↗", altstore: "AltStore ↗", keyTitle: "The important distinction", keyText: <>Use <strong>AltStore Classic</strong> on the iPhone — not AltStore PAL. Do not install AltStore on the Apple TV. The Apple TV version of Fusion is installed directly from the Mac using AltServer.</>, startLabel: "Start with your device", iphoneStart: "Set up iPhone", appleTvStart: "Set up Apple TV", backToTop: "Back to top ↑", onPage: "On this page",
    toc: ["What you need", "AltServer", "iPhone", "Fusion source", "7-day refresh", "Apple TV + Xcode", "tvOS IPA", "Sideloading", "Apple TV 7-day limit", "Recommended order", "Troubleshooting"], sections: ["What you need", "Install AltServer on the Mac", "iPhone: Install AltStore Classic", "iPhone: Add the Fusion source", "iPhone: 7-day refresh", "Apple TV: Install and pair Xcode", "Apple TV: Download the correct Fusion IPA", "Apple TV: Install Fusion with AltServer", "Apple TV: The 7-day limit", "Recommended order", "Quick troubleshooting"],
    needItems: ["A Mac running a supported version of macOS.", "An iPhone running iOS 26.0 or later.", "An Apple TV running tvOS 26.0 or later.", "An Apple Account. A free account is sufficient.", "AltServer installed on the Mac.", "AltStore Classic installed on the iPhone.", "Xcode on the Mac for the one-time Apple TV pairing."], packages: "Fusion provides separate packages:", iphone: "iPhone / iPad", appleTv: "Apple TV",
    altSteps: [<>Download <strong>AltServer for macOS</strong> from the official AltStore website.</>, <>Move <code>AltServer.app</code> into the Mac&apos;s <code>/Applications</code> folder.</>, "Launch AltServer.", "Check that the AltServer icon appears in the macOS menu bar."], officialSite: <>Official website: <a href="https://altstore.io/" target="_blank" rel="noreferrer">altstore.io ↗</a></>, flow: <>Mac + AltServer <span>→</span> iPhone <span>→</span> AltStore Classic <span>→</span> Fusion</>,
    iphoneSteps: ["Connect the iPhone to the Mac with a USB cable.", <>Unlock the iPhone and tap <strong>Trust</strong> if asked whether you trust this computer.</>, "Open the AltServer menu from the Mac menu bar.", <>Select <strong>Install AltStore</strong> and choose your iPhone.</>, "Enter the Apple Account requested by AltServer.", "Wait until AltStore appears on the iPhone."], trustTitle: "Trust the developer profile", trustText: <>On the iPhone, go to <strong>Settings → General → VPN &amp; Device Management</strong>. Open the profile for your Apple Account and choose <strong>Trust</strong>.</>, devTitle: "Enable Developer Mode", devText: <>On iOS 16 and later: <strong>Settings → Privacy &amp; Security → Developer Mode</strong>.</>, devSteps: ["Enable Developer Mode.", "Restart the iPhone when requested.", "Confirm Developer Mode after the restart."],
    sourceIntro: "Open AltStore Classic and add this source:", sourceSteps: ["Open AltStore Classic.", <>Open the <strong>Sources / Add Source</strong> screen.</>, "Add the URL shown above.", <>The source should appear as <strong>Exate&apos;s Fusion Cave</strong>.</>, <>Select <strong>Fusion</strong> — not <strong>Fusion (tvOS)</strong>.</>, "Install Fusion."], important: "Important:", sourceWarning: "AltServer must be reachable from the iPhone while AltStore installs or refreshes an app. The easiest setup is to keep the Mac running AltServer and have the Mac and iPhone on the same Wi-Fi network.",
    refreshText: "With a free Apple developer account, sideloaded apps expire after seven days unless they are refreshed.", refreshLabel: "For the refresh to work:", refreshItems: ["AltServer is running on the Mac.", "The iPhone can reach that Mac, normally over the same Wi-Fi network."], refreshEnd: <>You can also open AltStore Classic and manually press <strong>Refresh All</strong>. A free account also has Apple&apos;s normal limit of three active sideloaded apps at once. AltStore itself counts toward that limit.</>,
    pairingIntro: "The Apple TV must first be paired with Xcode. This is a one-time setup unless the pairing is later removed.", pairingSteps: ["Install Xcode from Apple on the Mac.", "Make sure the Mac and Apple TV are on the same local network.", <>On Apple TV, open <strong>Settings → Remotes and Devices → Remote App and Devices</strong>.</>, <>Open Xcode and choose <strong>Window → Devices and Simulators</strong>.</>, "Find the Apple TV under the available or discovered devices.", "Select it and complete pairing using the code displayed on the Apple TV.", "Wait until Xcode shows the Apple TV as paired or connected."], noAltStore: <>You do <strong>not</strong> install AltStore Classic on the Apple TV. Xcode is only needed so the Mac can pair with the Apple TV; AltServer then performs the IPA installation.</>,
    releaseIntro: <>Download the current Apple TV build from the <a href="https://github.com/yodaluca23/Fusion-AltStore/releases" target="_blank" rel="noreferrer">Fusion GitHub Releases page ↗</a>.</>, forAppleTv: "For Apple TV", download: "Download ↗", wrongIpa: <> <strong>Do not use:</strong> <code>Fusion-unsigned-ios.ipa</code> is for iPhone/iPad, not Apple TV.</>, sideloadSteps: ["Make sure AltServer is running on the Mac.", "Make sure the Apple TV remains paired and reachable on the local network.", <>Hold the <strong>Option (⌥)</strong> key while opening the AltServer menu in the macOS menu bar.</>, <>Choose <strong>Sideload .ipa…</strong>.</>, <>Select <code>Fusion-tvos-unsigned.ipa</code>.</>, "Select the paired Apple TV as the target device.", "Enter your Apple Account credentials if AltServer requests them.", "Wait for AltServer to finish signing and installing Fusion.", "Fusion should then appear on the Apple TV Home Screen."], sevenTv: "With a free Apple developer account, the Apple TV app is also signed for seven days.", noAuto: <>Unlike Fusion on the iPhone, an IPA installed directly on Apple TV using AltServer does not receive AltStore&apos;s normal automatic refresh workflow.</>, repeat: "Before or after the seven days expire, repeat:", repeatEnd: "You do not normally need to delete Fusion first.",
    orderItems: [["Mac", "Install and launch AltServer."], ["iPhone", "Install AltStore Classic from AltServer."], ["iPhone", "Trust the developer profile and enable Developer Mode."], ["iPhone", "Add the Fusion source and install Fusion."], ["Mac", "Install or open Xcode."], ["Apple TV", "Pair Apple TV with Xcode."], ["Mac → Apple TV", "Use AltServer's Sideload .ipa command with the tvOS Fusion IPA."]],
    trouble: [{ title: "AltServer cannot see the iPhone", items: ["Connect it by USB first.", "Unlock the iPhone.", "Confirm Trust This Computer.", "Restart AltServer if necessary."] }, { title: "Fusion will not install or refresh", items: ["Confirm AltServer is running.", "Put the Mac and iPhone on the same Wi-Fi network.", "Try connecting the iPhone by USB.", "Check that Developer Mode is enabled."] }, { title: "The Apple TV does not appear in AltServer", items: ["Confirm it is paired in Xcode first.", "Confirm the Mac and Apple TV are on the same local network.", "Open Settings → Remotes and Devices → Remote App and Devices on the Apple TV and retry pairing.", "Quit and reopen AltServer after the Xcode pairing is complete."] }, { title: "Fusion suddenly stops opening after several days", text: "The signing period probably expired.", items: ["iPhone: refresh Fusion in AltStore Classic.", "Apple TV: sideload the tvOS IPA again through AltServer."] }], sourcesTitle: "Checked sources", sourceLinks: ["AltStore: macOS installation", "AltServer documentation / release notes", "AltStore Classic documentation", "Fusion-AltStore source.json", "Fusion releases on GitHub"], reviewed: "Reviewed against the available AltStore documentation and Fusion source/release metadata on 9 August 2026."
  },
  de: {
    eyebrow: "FUSION · INSTALLATIONSANLEITUNG", title: <>Fusion auf iPhone<br />und Apple TV installieren.</>, lead: "Die vollständige Anleitung — Schritt für Schritt mit AltStore Classic, AltServer und Xcode.", releases: "Fusion-Releases ↗", altstore: "AltStore ↗", keyTitle: "Die entscheidende Unterscheidung", keyText: <>Auf dem iPhone verwendest du <strong>AltStore Classic</strong> — nicht AltStore PAL. Auf dem Apple TV wird AltStore nicht installiert: Dort installierst du Fusion direkt vom Mac über AltServer.</>, startLabel: "Starte mit deinem Gerät", iphoneStart: "iPhone einrichten", appleTvStart: "Apple TV einrichten", backToTop: "Nach oben ↑", onPage: "Auf dieser Seite",
    toc: ["Was du brauchst", "AltServer", "iPhone", "Fusion-Quelle", "7-Tage-Erneuerung", "Apple TV + Xcode", "tvOS-IPA", "Installation", "Apple TV: 7-Tage-Limit", "Reihenfolge", "Fehlerbehebung"], sections: ["Was du brauchst", "AltServer auf dem Mac installieren", "iPhone: AltStore Classic installieren", "iPhone: Fusion-Quelle hinzufügen", "iPhone: Apps nach sieben Tagen erneuern", "Apple TV: Mit Xcode koppeln", "Apple TV: Die richtige Fusion-IPA laden", "Apple TV: Fusion mit AltServer installieren", "Apple TV: Das 7-Tage-Limit", "Empfohlene Reihenfolge", "Schnelle Fehlerbehebung"],
    needItems: ["Mac mit einer unterstützten macOS-Version", "iPhone mit iOS 26.0 oder neuer", "Apple TV mit tvOS 26.0 oder neuer", "Apple Account — ein kostenloser Account reicht", "AltServer auf dem Mac", "AltStore Classic auf dem iPhone", "Xcode auf dem Mac zur einmaligen Kopplung mit Apple TV"], packages: "Für Fusion gibt es zwei getrennte Installationsdateien:", iphone: "iPhone / iPad", appleTv: "Apple TV", altSteps: [<><strong>AltServer für macOS</strong> von der offiziellen AltStore-Website herunterladen.</>, <><code>AltServer.app</code> in den Ordner <code>/Applications</code> verschieben.</>, "AltServer starten.", "Prüfen, ob das AltServer-Symbol in der macOS-Menüleiste erscheint."], officialSite: <>Offizielle Website: <a href="https://altstore.io/" target="_blank" rel="noreferrer">altstore.io ↗</a></>, flow: <>Mac + AltServer <span>→</span> iPhone <span>→</span> AltStore Classic <span>→</span> Fusion</>,
    iphoneSteps: ["iPhone per USB-Kabel mit dem Mac verbinden.", <>iPhone entsperren und bei der Abfrage <strong>Diesem Computer vertrauen</strong> bestätigen.</>, "AltServer in der macOS-Menüleiste öffnen.", <><strong>Install AltStore</strong> wählen und dein iPhone auswählen.</>, "Mit dem Apple Account anmelden, nach dem AltServer fragt.", "Warten, bis AltStore auf dem iPhone erscheint."], trustTitle: "Dem Entwicklerprofil vertrauen", trustText: <>Auf dem iPhone zu <strong>Einstellungen → Allgemein → VPN &amp; Geräteverwaltung</strong> gehen. Das Profil deines Apple Accounts öffnen und <strong>Vertrauen</strong> auswählen.</>, devTitle: "Entwicklermodus aktivieren", devText: <>Ab iOS 16: <strong>Einstellungen → Datenschutz &amp; Sicherheit → Entwicklermodus</strong>.</>, devSteps: ["Entwicklermodus aktivieren.", "Das iPhone neu starten, wenn du dazu aufgefordert wirst.", "Den Entwicklermodus nach dem Neustart bestätigen."],
    sourceIntro: "AltStore Classic öffnen und diese Quelle hinzufügen:", sourceSteps: ["AltStore Classic öffnen.", <>Den Bereich <strong>Sources → Add Source</strong> öffnen.</>, "Die oben angezeigte URL einfügen.", <>Die Quelle <strong>Exate&apos;s Fusion Cave</strong> sollte nun erscheinen.</>, <><strong>Fusion</strong> auswählen — nicht <strong>Fusion (tvOS)</strong>.</>, "Fusion installieren."], important: "Wichtig:", sourceWarning: "AltServer muss vom iPhone aus erreichbar sein, wenn AltStore Fusion installiert oder erneuert. Am einfachsten: AltServer auf dem Mac laufen lassen und Mac sowie iPhone mit demselben WLAN verbinden.", refreshText: "Mit einem kostenlosen Apple Account müssen Apps, die über AltStore installiert wurden, innerhalb von sieben Tagen erneuert werden. Andernfalls lassen sie sich nicht mehr öffnen.", refreshLabel: "Damit die Erneuerung klappt:", refreshItems: ["AltServer läuft auf dem Mac.", "Das iPhone kann den Mac erreichen — normalerweise über dasselbe WLAN."], refreshEnd: <>Du kannst AltStore Classic öffnen und <strong>Refresh All</strong> manuell ausführen. Mit einem kostenlosen Account sind höchstens drei über AltStore installierte Apps gleichzeitig aktiv; AltStore selbst zählt dabei mit.</>,
    pairingIntro: "Bevor Fusion installiert werden kann, musst du das Apple TV einmal mit Xcode auf deinem Mac koppeln. Die Kopplung bleibt normalerweise bestehen.", pairingSteps: ["Xcode von Apple auf dem Mac installieren.", "Mac und Apple TV mit demselben lokalen Netzwerk verbinden.", <>Auf dem Apple TV <strong>Einstellungen → Fernbedienungen und Geräte → Remote-App und Geräte</strong> öffnen.</>, <>Xcode öffnen und <strong>Window → Devices and Simulators</strong> wählen.</>, "Das Apple TV in der Liste der gefundenen Geräte auswählen.", "Den auf dem Apple TV angezeigten Code eingeben, um die Kopplung abzuschließen.", "Warten, bis Xcode das Apple TV als verbunden anzeigt."], noAltStore: <>Auf dem Apple TV wird <strong>kein AltStore Classic</strong> installiert. Xcode stellt nur die Kopplung zwischen Mac und Apple TV her; anschließend übernimmt AltServer die IPA-Installation.</>, releaseIntro: <>Die aktuelle Apple-TV-Version lädst du von der <a href="https://github.com/yodaluca23/Fusion-AltStore/releases" target="_blank" rel="noreferrer">Fusion-Releases-Seite auf GitHub ↗</a> herunter.</>, forAppleTv: "Für Apple TV", download: "Herunterladen ↗", wrongIpa: <><strong>Nicht verwenden:</strong> <code>Fusion-unsigned-ios.ipa</code> ist für iPhone/iPad, nicht für Apple TV.</>, sideloadSteps: ["AltServer muss auf dem Mac laufen.", "Das gekoppelte Apple TV muss im lokalen Netzwerk erreichbar sein.", <>Die <strong>Option-Taste (⌥)</strong> gedrückt halten, während du das AltServer-Menü in der macOS-Menüleiste öffnest.</>, <><strong>Sideload .ipa…</strong> auswählen.</>, <><code>Fusion-tvos-unsigned.ipa</code> auswählen.</>, "Das gekoppelte Apple TV als Zielgerät auswählen.", "Die Zugangsdaten deines Apple Accounts eingeben, falls AltServer danach fragt.", "Warten, bis AltServer Fusion signiert und installiert hat.", "Fusion sollte danach auf dem Home-Bildschirm des Apple TV erscheinen."], sevenTv: "Bei einem kostenlosen Apple Account ist die Signatur der Apple-TV-App ebenfalls sieben Tage gültig.", noAuto: <>Im Unterschied zum iPhone kann eine IPA, die über AltServer direkt auf Apple TV installiert wurde, nicht automatisch über AltStore erneuert werden.</>, repeat: "Vor Ablauf der sieben Tage wiederholst du diesen Vorgang:", repeatEnd: "Du musst Fusion dafür normalerweise nicht vorher löschen.",
    orderItems: [["💻 Mac", "AltServer installieren und starten"], ["📱 iPhone", "AltStore Classic über AltServer installieren"], ["📱 iPhone", "Dem Profil vertrauen und den Entwicklermodus aktivieren"], ["📱 iPhone", "Fusion-Quelle hinzufügen und Fusion installieren"], ["💻 Mac", "Xcode installieren und öffnen"], ["📺 Apple TV", "Mit Xcode koppeln"], ["💻 Mac → 📺 Apple TV", "Die tvOS-IPA über Sideload .ipa… in AltServer installieren"]], trouble: [{ title: "AltServer erkennt das iPhone nicht", items: ["iPhone zuerst per USB verbinden.", "iPhone entsperren.", "Diesem Computer vertrauen bestätigen.", "AltServer gegebenenfalls neu starten."] }, { title: "Fusion lässt sich nicht installieren oder erneuern", items: ["Prüfen, ob AltServer läuft.", "Mac und iPhone mit demselben WLAN verbinden.", "iPhone testweise per USB verbinden.", "Prüfen, ob der Entwicklermodus aktiviert ist."] }, { title: "Apple TV erscheint nicht in AltServer", items: ["Das Apple TV zuerst in Xcode koppeln.", "Prüfen, ob beide Geräte im selben lokalen Netzwerk sind.", "Auf Apple TV: Einstellungen → Fernbedienungen und Geräte → Remote-App und Geräte öffnen.", "AltServer nach der erfolgreichen Kopplung schließen und erneut öffnen."] }, { title: "Fusion startet nach einigen Tagen nicht mehr", text: "Wahrscheinlich ist die Signatur abgelaufen.", items: ["iPhone: Fusion in AltStore Classic erneuern.", "Apple TV: Die tvOS-IPA erneut über AltServer installieren."] }], sourcesTitle: "Geprüfte Quellen", sourceLinks: ["AltStore: macOS-Installation", "AltServer-Dokumentation / Release Notes", "AltStore Classic-Dokumentation", "Fusion-AltStore-Quellendatei (source.json)", "Fusion-Releases auf GitHub"], reviewed: "Abgeglichen mit der verfügbaren AltStore-Dokumentation sowie den Quell- und Release-Metadaten von Fusion am 9. August 2026."
  }
} as const;

// These two editions intentionally inherit the URLs and package names from the
// English source, while every reader-facing string is translated below.
const translatedCopy = {
  es: {
    ...copy.en,
    eyebrow: "FUSION · GUÍA DE INSTALACIÓN", title: <>Instala Fusion en el iPhone<br />y el Apple TV.</>, lead: "La guía completa paso a paso con AltStore Classic, AltServer y Xcode.", releases: "Versiones de Fusion ↗", altstore: "AltStore ↗", keyTitle: "La diferencia importante", keyText: <>Usa <strong>AltStore Classic</strong> en el iPhone, no AltStore PAL. No instales AltStore en el Apple TV: allí Fusion se instala directamente desde el Mac con AltServer.</>, startLabel: "Empieza con tu dispositivo", iphoneStart: "Configurar el iPhone", appleTvStart: "Configurar el Apple TV", backToTop: "Volver arriba ↑", onPage: "En esta página",
    toc: ["Lo que necesitas", "AltServer", "iPhone", "Fuente de Fusion", "Renovación a 7 días", "Apple TV + Xcode", "IPA de tvOS", "Instalación", "Límite de 7 días del Apple TV", "Orden recomendado", "Solución de problemas"], sections: ["Lo que necesitas", "Instalar AltServer en el Mac", "iPhone: instalar AltStore Classic", "iPhone: añadir la fuente de Fusion", "iPhone: renovar las apps cada 7 días", "Apple TV: vincular con Xcode", "Apple TV: descargar el IPA correcto de Fusion", "Apple TV: instalar Fusion con AltServer", "Apple TV: el límite de 7 días", "Orden recomendado", "Solución rápida de problemas"],
    needItems: ["Un Mac con una versión compatible de macOS.", "Un iPhone con iOS 26.0 o posterior.", "Un Apple TV con tvOS 26.0 o posterior.", "Una cuenta de Apple. Basta con una cuenta gratuita.", "AltServer instalado en el Mac.", "AltStore Classic instalado en el iPhone.", "Xcode en el Mac para la vinculación inicial con el Apple TV."], packages: "Fusion ofrece dos paquetes distintos:", iphone: "iPhone / iPad", appleTv: "Apple TV",
    altSteps: [<>Descarga <strong>AltServer para macOS</strong> desde el sitio oficial de AltStore.</>, <>Mueve <code>AltServer.app</code> a la carpeta <code>/Applications</code> del Mac.</>, "Inicia AltServer.", "Comprueba que el icono de AltServer aparezca en la barra de menús de macOS."], officialSite: <>Sitio oficial: <a href="https://altstore.io/" target="_blank" rel="noreferrer">altstore.io ↗</a></>, flow: <>Mac + AltServer <span>→</span> iPhone <span>→</span> AltStore Classic <span>→</span> Fusion</>,
    iphoneSteps: ["Conecta el iPhone al Mac con un cable USB.", <>Desbloquea el iPhone y pulsa <strong>Confiar</strong> si te pregunta si confías en este ordenador.</>, "Abre el menú de AltServer en la barra de menús del Mac.", <>Selecciona <strong>Install AltStore</strong> y elige tu iPhone.</>, "Introduce la cuenta de Apple que solicite AltServer.", "Espera a que AltStore aparezca en el iPhone."], trustTitle: "Confiar en el perfil de desarrollador", trustText: <>En el iPhone, ve a <strong>Ajustes → General → VPN y gestión de dispositivos</strong>. Abre el perfil de tu cuenta de Apple y selecciona <strong>Confiar</strong>.</>, devTitle: "Activar el modo de desarrollador", devText: <>Desde iOS 16: <strong>Ajustes → Privacidad y seguridad → Modo de desarrollador</strong>.</>, devSteps: ["Activa el modo de desarrollador.", "Reinicia el iPhone cuando se te solicite.", "Confirma el modo de desarrollador tras el reinicio."],
    sourceIntro: "Abre AltStore Classic y añade esta fuente:", sourceSteps: ["Abre AltStore Classic.", <>Abre <strong>Sources / Add Source</strong>.</>, "Añade la URL mostrada arriba.", <>Debería aparecer la fuente <strong>Exate&apos;s Fusion Cave</strong>.</>, <>Selecciona <strong>Fusion</strong>, no <strong>Fusion (tvOS)</strong>.</>, "Instala Fusion."], important: "Importante:", sourceWarning: "El iPhone debe poder acceder a AltServer cuando AltStore instale o renueve Fusion. Lo más fácil es mantener AltServer activo en el Mac y conectar el Mac y el iPhone a la misma red Wi-Fi.",
    refreshText: "Con una cuenta gratuita de desarrollador de Apple, las apps instaladas mediante AltStore caducan a los siete días si no se renuevan.", refreshLabel: "Para que la renovación funcione:", refreshItems: ["AltServer está en ejecución en el Mac.", "El iPhone puede acceder a ese Mac, normalmente a través de la misma red Wi-Fi."], refreshEnd: <>También puedes abrir AltStore Classic y pulsar manualmente <strong>Refresh All</strong>. Una cuenta gratuita tiene además el límite habitual de Apple de tres apps instaladas de este modo a la vez. AltStore cuenta dentro de ese límite.</>,
    pairingIntro: "Primero debes vincular el Apple TV con Xcode. Es una configuración de una sola vez, salvo que elimines la vinculación más adelante.", pairingSteps: ["Instala Xcode de Apple en el Mac.", "Asegúrate de que el Mac y el Apple TV estén en la misma red local.", <>En el Apple TV, abre <strong>Ajustes → Mandos y dispositivos → App Remote y dispositivos</strong>.</>, <>Abre Xcode y selecciona <strong>Window → Devices and Simulators</strong>.</>, "Busca el Apple TV entre los dispositivos disponibles o detectados.", "Selecciónalo y completa la vinculación con el código que aparece en el Apple TV.", "Espera a que Xcode muestre el Apple TV como vinculado o conectado."], noAltStore: <>No instales <strong>AltStore Classic</strong> en el Apple TV. Xcode solo sirve para que el Mac se vincule al Apple TV; AltServer realiza después la instalación del IPA.</>,
    releaseIntro: <>Descarga la versión actual para Apple TV desde la <a href="https://github.com/yodaluca23/Fusion-AltStore/releases" target="_blank" rel="noreferrer">página de versiones de Fusion en GitHub ↗</a>.</>, forAppleTv: "Para Apple TV", download: "Descargar ↗", wrongIpa: <><strong>No uses:</strong> <code>Fusion-unsigned-ios.ipa</code> es para iPhone/iPad, no para Apple TV.</>, sideloadSteps: ["Comprueba que AltServer esté funcionando en el Mac.", "Comprueba que el Apple TV siga vinculado y accesible en la red local.", <>Mantén pulsada la tecla <strong>Opción (⌥)</strong> mientras abres el menú de AltServer en la barra de menús de macOS.</>, <>Elige <strong>Sideload .ipa…</strong>.</>, <>Selecciona <code>Fusion-tvos-unsigned.ipa</code>.</>, "Selecciona el Apple TV vinculado como dispositivo de destino.", "Introduce las credenciales de tu cuenta de Apple si AltServer las solicita.", "Espera a que AltServer termine de firmar e instalar Fusion.", "Fusion debería aparecer entonces en la pantalla de inicio del Apple TV."], sevenTv: "Con una cuenta gratuita de desarrollador de Apple, la app del Apple TV también queda firmada durante siete días.", noAuto: <>A diferencia de Fusion en el iPhone, un IPA instalado directamente en el Apple TV mediante AltServer no tiene el flujo normal de renovación automática de AltStore.</>, repeat: "Antes o después de que pasen los siete días, repite:", repeatEnd: "Normalmente no necesitas borrar Fusion primero.",
    orderItems: [["💻 Mac", "Instala e inicia AltServer."], ["📱 iPhone", "Instala AltStore Classic desde AltServer."], ["📱 iPhone", "Confía en el perfil de desarrollador y activa el modo de desarrollador."], ["📱 iPhone", "Añade la fuente de Fusion e instala Fusion."], ["💻 Mac", "Instala o abre Xcode."], ["📺 Apple TV", "Vincula el Apple TV con Xcode."], ["💻 Mac → 📺 Apple TV", "Usa Sideload .ipa de AltServer con el IPA de Fusion para tvOS."]],
    trouble: [{ title: "AltServer no detecta el iPhone", items: ["Conéctalo primero por USB.", "Desbloquea el iPhone.", "Confirma Confiar en este ordenador.", "Reinicia AltServer si hace falta."] }, { title: "Fusion no se instala o no se renueva", items: ["Confirma que AltServer esté activo.", "Conecta el Mac y el iPhone a la misma red Wi-Fi.", "Prueba a conectar el iPhone por USB.", "Comprueba que el modo de desarrollador esté activado."] }, { title: "El Apple TV no aparece en AltServer", items: ["Comprueba primero que esté vinculado en Xcode.", "Comprueba que el Mac y el Apple TV estén en la misma red local.", "En el Apple TV, abre Ajustes → Mandos y dispositivos → App Remote y dispositivos e intenta vincularlo de nuevo.", "Cierra y vuelve a abrir AltServer tras completar la vinculación con Xcode."] }, { title: "Fusion deja de abrirse tras varios días", text: "Probablemente haya caducado el periodo de firma.", items: ["iPhone: renueva Fusion en AltStore Classic.", "Apple TV: vuelve a instalar el IPA de tvOS mediante AltServer."] }], sourcesTitle: "Fuentes comprobadas", sourceLinks: ["AltStore: instalación en macOS", "Documentación / notas de versión de AltServer", "Documentación de AltStore Classic", "source.json de Fusion-AltStore", "Versiones de Fusion en GitHub"], reviewed: "Comprobado con la documentación disponible de AltStore y los metadatos de fuente y versiones de Fusion el 9 de agosto de 2026."
  },
  fr: {
    ...copy.en,
    eyebrow: "FUSION · GUIDE D’INSTALLATION", title: <>Installer Fusion sur iPhone<br />et Apple TV.</>, lead: "Le guide complet, étape par étape, avec AltStore Classic, AltServer et Xcode.", releases: "Versions de Fusion ↗", altstore: "AltStore ↗", keyTitle: "La distinction essentielle", keyText: <>Utilise <strong>AltStore Classic</strong> sur l’iPhone, pas AltStore PAL. N’installe pas AltStore sur l’Apple TV : Fusion y est installée directement depuis le Mac avec AltServer.</>, startLabel: "Commence avec ton appareil", iphoneStart: "Configurer l’iPhone", appleTvStart: "Configurer l’Apple TV", backToTop: "Retour en haut ↑", onPage: "Sur cette page",
    toc: ["Ce qu’il faut", "AltServer", "iPhone", "Source Fusion", "Renouvellement à 7 jours", "Apple TV + Xcode", "IPA tvOS", "Installation", "Limite de 7 jours Apple TV", "Ordre recommandé", "Dépannage"], sections: ["Ce qu’il faut", "Installer AltServer sur le Mac", "iPhone : installer AltStore Classic", "iPhone : ajouter la source Fusion", "iPhone : renouveler les apps après 7 jours", "Apple TV : jumeler avec Xcode", "Apple TV : télécharger le bon IPA Fusion", "Apple TV : installer Fusion avec AltServer", "Apple TV : la limite de 7 jours", "Ordre recommandé", "Dépannage rapide"],
    needItems: ["Un Mac avec une version compatible de macOS.", "Un iPhone sous iOS 26.0 ou version ultérieure.", "Une Apple TV sous tvOS 26.0 ou version ultérieure.", "Un compte Apple. Un compte gratuit suffit.", "AltServer installé sur le Mac.", "AltStore Classic installé sur l’iPhone.", "Xcode sur le Mac pour le jumelage unique avec l’Apple TV."], packages: "Fusion propose deux paquets distincts :", iphone: "iPhone / iPad", appleTv: "Apple TV",
    altSteps: [<>Télécharge <strong>AltServer pour macOS</strong> depuis le site officiel d’AltStore.</>, <>Déplace <code>AltServer.app</code> dans le dossier <code>/Applications</code> du Mac.</>, "Lance AltServer.", "Vérifie que l’icône AltServer apparaît dans la barre des menus de macOS."], officialSite: <>Site officiel : <a href="https://altstore.io/" target="_blank" rel="noreferrer">altstore.io ↗</a></>, flow: <>Mac + AltServer <span>→</span> iPhone <span>→</span> AltStore Classic <span>→</span> Fusion</>,
    iphoneSteps: ["Connecte l’iPhone au Mac avec un câble USB.", <>Déverrouille l’iPhone et touche <strong>Faire confiance</strong> si l’on te demande si tu fais confiance à cet ordinateur.</>, "Ouvre le menu AltServer dans la barre des menus du Mac.", <>Choisis <strong>Install AltStore</strong> puis ton iPhone.</>, "Saisis le compte Apple demandé par AltServer.", "Attends qu’AltStore apparaisse sur l’iPhone."], trustTitle: "Faire confiance au profil développeur", trustText: <>Sur l’iPhone, va dans <strong>Réglages → Général → VPN et gestion de l’appareil</strong>. Ouvre le profil de ton compte Apple, puis choisis <strong>Faire confiance</strong>.</>, devTitle: "Activer le mode développeur", devText: <>À partir d’iOS 16 : <strong>Réglages → Confidentialité et sécurité → Mode développeur</strong>.</>, devSteps: ["Active le mode développeur.", "Redémarre l’iPhone lorsqu’il te le demande.", "Confirme le mode développeur après le redémarrage."],
    sourceIntro: "Ouvre AltStore Classic et ajoute cette source :", sourceSteps: ["Ouvre AltStore Classic.", <>Ouvre l’écran <strong>Sources / Add Source</strong>.</>, "Ajoute l’URL affichée ci-dessus.", <>La source <strong>Exate&apos;s Fusion Cave</strong> devrait apparaître.</>, <>Sélectionne <strong>Fusion</strong>, pas <strong>Fusion (tvOS)</strong>.</>, "Installe Fusion."], important: "Important :", sourceWarning: "L’iPhone doit pouvoir joindre AltServer pendant l’installation ou le renouvellement de Fusion par AltStore. Le plus simple est de laisser AltServer ouvert sur le Mac et de connecter le Mac et l’iPhone au même réseau Wi-Fi.",
    refreshText: "Avec un compte développeur Apple gratuit, les apps installées avec AltStore expirent après sept jours si elles ne sont pas renouvelées.", refreshLabel: "Pour que le renouvellement fonctionne :", refreshItems: ["AltServer est lancé sur le Mac.", "L’iPhone peut joindre ce Mac, généralement par le même réseau Wi-Fi."], refreshEnd: <>Tu peux aussi ouvrir AltStore Classic et appuyer manuellement sur <strong>Refresh All</strong>. Un compte gratuit est aussi soumis à la limite Apple habituelle de trois apps sideloadées actives en même temps. AltStore compte dans cette limite.</>,
    pairingIntro: "L’Apple TV doit d’abord être jumelée avec Xcode. Cette configuration est unique, sauf si le jumelage est supprimé par la suite.", pairingSteps: ["Installe Xcode d’Apple sur le Mac.", "Vérifie que le Mac et l’Apple TV sont sur le même réseau local.", <>Sur l’Apple TV, ouvre <strong>Réglages → Télécommandes et appareils → App Remote et appareils</strong>.</>, <>Ouvre Xcode et choisis <strong>Window → Devices and Simulators</strong>.</>, "Trouve l’Apple TV parmi les appareils disponibles ou détectés.", "Sélectionne-la et termine le jumelage avec le code affiché sur l’Apple TV.", "Attends que Xcode affiche l’Apple TV comme jumelée ou connectée."], noAltStore: <>N’installe <strong>pas AltStore Classic</strong> sur l’Apple TV. Xcode sert seulement à jumeler le Mac et l’Apple TV ; AltServer installe ensuite l’IPA.</>,
    releaseIntro: <>Télécharge la version Apple TV actuelle depuis la <a href="https://github.com/yodaluca23/Fusion-AltStore/releases" target="_blank" rel="noreferrer">page GitHub des versions de Fusion ↗</a>.</>, forAppleTv: "Pour Apple TV", download: "Télécharger ↗", wrongIpa: <><strong>Ne pas utiliser :</strong> <code>Fusion-unsigned-ios.ipa</code> est destiné à l’iPhone/iPad, pas à l’Apple TV.</>, sideloadSteps: ["Vérifie qu’AltServer est lancé sur le Mac.", "Vérifie que l’Apple TV reste jumelée et accessible sur le réseau local.", <>Maintiens la touche <strong>Option (⌥)</strong> enfoncée pendant que tu ouvres le menu AltServer dans la barre des menus de macOS.</>, <>Choisis <strong>Sideload .ipa…</strong>.</>, <>Sélectionne <code>Fusion-tvos-unsigned.ipa</code>.</>, "Choisis l’Apple TV jumelée comme appareil cible.", "Saisis les identifiants du compte Apple si AltServer les demande.", "Attends qu’AltServer ait fini de signer et d’installer Fusion.", "Fusion devrait alors apparaître sur l’écran d’accueil de l’Apple TV."], sevenTv: "Avec un compte développeur Apple gratuit, l’app Apple TV est elle aussi signée pendant sept jours.", noAuto: <>Contrairement à Fusion sur l’iPhone, un IPA installé directement sur l’Apple TV avec AltServer ne bénéficie pas du renouvellement automatique habituel d’AltStore.</>, repeat: "Avant ou après l’expiration des sept jours, répète :", repeatEnd: "Il n’est normalement pas nécessaire de supprimer Fusion d’abord.",
    orderItems: [["💻 Mac", "Installe et lance AltServer."], ["📱 iPhone", "Installe AltStore Classic depuis AltServer."], ["📱 iPhone", "Fais confiance au profil et active le mode développeur."], ["📱 iPhone", "Ajoute la source Fusion et installe Fusion."], ["💻 Mac", "Installe ou ouvre Xcode."], ["📺 Apple TV", "Jumelle l’Apple TV avec Xcode."], ["💻 Mac → 📺 Apple TV", "Utilise la commande Sideload .ipa d’AltServer avec l’IPA Fusion tvOS."]],
    trouble: [{ title: "AltServer ne voit pas l’iPhone", items: ["Connecte-le d’abord en USB.", "Déverrouille l’iPhone.", "Confirme Faire confiance à cet ordinateur.", "Redémarre AltServer si nécessaire."] }, { title: "Fusion ne s’installe pas ou ne se renouvelle pas", items: ["Vérifie qu’AltServer est lancé.", "Place le Mac et l’iPhone sur le même réseau Wi-Fi.", "Essaie de connecter l’iPhone en USB.", "Vérifie que le mode développeur est activé."] }, { title: "L’Apple TV n’apparaît pas dans AltServer", items: ["Vérifie d’abord qu’elle est jumelée dans Xcode.", "Vérifie que le Mac et l’Apple TV sont sur le même réseau local.", "Sur l’Apple TV, ouvre Réglages → Télécommandes et appareils → App Remote et appareils, puis essaie à nouveau de jumeler.", "Ferme puis rouvre AltServer une fois le jumelage Xcode terminé."] }, { title: "Fusion cesse de s’ouvrir après quelques jours", text: "La période de signature a probablement expiré.", items: ["iPhone : renouvelle Fusion dans AltStore Classic.", "Apple TV : installe à nouveau l’IPA tvOS avec AltServer."] }], sourcesTitle: "Sources vérifiées", sourceLinks: ["AltStore : installation macOS", "Documentation / notes de version d’AltServer", "Documentation d’AltStore Classic", "source.json de Fusion-AltStore", "Versions de Fusion sur GitHub"], reviewed: "Vérifié par rapport à la documentation AltStore disponible et aux métadonnées de source et de versions de Fusion le 9 août 2026."
  }
} as const;

const guides = { ...copy, ...translatedCopy } as const;
const guideLibraryLabels: Record<Lang, string> = { en: "All guides", de: "Alle Anleitungen", es: "Todas las guías", fr: "Tous les guides" };
const verificationLabels: Record<Lang, string> = { en: "Guide verification notes", de: "Prüfnotizen zur Anleitung", es: "Notas de verificación de la guía", fr: "Notes de vérification du guide" };

function Section({ id, number, title, children }: { id: string; number: string; title: string; children: React.ReactNode }) { return <section id={id} className="section"><div className="section-kicker">{number}</div><h2>{title}</h2>{children}</section>; }
function Note({ children, warning = false }: { children: React.ReactNode; warning?: boolean }) { return <div className={warning ? "callout warning" : "callout note"}>{children}</div>; }
function Checklist({ items }: { items: readonly string[] }) { const [checked, setChecked] = useState(() => items.map(() => false)); return <ul className="checklist">{items.map((item, index) => <li key={item}><label><input type="checkbox" checked={checked[index]} onChange={() => setChecked((state) => state.map((value, position) => position === index ? !value : value))} /><span>{item}</span></label></li>)}</ul>; }
function CopySource({ lang }: { lang: Lang }) {
  const labels: Record<Lang, [string, string]> = { en: ["Copy", "Copied"], de: ["Kopieren", "Kopiert"], es: ["Copiar", "Copiado"], fr: ["Copier", "Copié"] };
  const [copied, setCopied] = useState(false);
  const [copyLabel, copiedLabel] = labels[lang];
  async function copySource() {
    try { await navigator.clipboard.writeText(sourceUrl); }
    catch { const area = document.createElement("textarea"); area.value = sourceUrl; document.body.appendChild(area); area.select(); document.execCommand("copy"); area.remove(); }
    setCopied(true); window.setTimeout(() => setCopied(false), 1800);
  }
  return <div className="code-box"><code>{sourceUrl}</code><button type="button" onClick={copySource} aria-live="polite">{copied ? `✓ ${copiedLabel}` : `⧉ ${copyLabel}`}</button></div>;
}

export default function FusionGuide({ initialLang }: { initialLang: Lang }) {
  const lang = initialLang;
  const t = guides[lang];
  const ids = ["needs", "altserver", "iphone", "source", "refresh", "xcode", "ipa", "sideload", "tv-refresh", "order", "trouble"];
  const links = ["https://faq.altstore.io/altstore-classic/how-to-install-altstore-macos", "https://faq.altstore.io/release-notes/altserver", "https://faq.altstore.io/altstore-classic/altserver", sourceUrl, "https://github.com/yodaluca23/Fusion-AltStore/releases"];
  return <main id="top">
    <nav className="guide-nav" aria-label={guideLibraryLabels[lang]}><Link href={languageHref(lang, "hub")}>← {guideLibraryLabels[lang]}</Link><a href="https://github.com/berot3/ios-tvos-sideloading-guides">GitHub ↗</a></nav>
    <header className="hero"><div className="hero-top"><div className="eyebrow">{t.eyebrow}</div><LanguageSwitcher lang={lang} route="fusion" detectLanguage={initialLang === "en"} /></div><h1>{t.title}</h1><p className="lead">{t.lead}</p><div className="hero-links"><a href="https://github.com/yodaluca23/Fusion-AltStore/releases" target="_blank" rel="noreferrer">{t.releases}</a><a href="https://altstore.io/" target="_blank" rel="noreferrer">{t.altstore}</a></div></header>
    <Note><strong>{t.keyTitle}</strong><br />{t.keyText}</Note>
    <div className="start-here"><p>{t.startLabel}</p><div><a href="#iphone">{t.iphoneStart} <span>→</span></a><a href="#xcode">{t.appleTvStart} <span>→</span></a></div></div>
    <nav className="toc" aria-label={t.onPage}><div className="toc-title">{t.onPage}</div><div className="toc-grid">{t.toc.map((label, i) => <a key={label} href={`#${ids[i]}`}>{label}</a>)}</div></nav>
    <Section id="needs" number="01" title={t.sections[0]}><div className="card"><Checklist items={t.needItems} /></div><p>{t.packages}</p><div className="ipa-grid"><div><span>{t.iphone}</span><code>Fusion-unsigned-ios.ipa</code></div><div><span>{t.appleTv}</span><code>Fusion-tvos-unsigned.ipa</code></div></div></Section>
    <Section id="altserver" number="02" title={t.sections[1]}><ol>{t.altSteps.map((x, i) => <li key={i}><span>{x}</span></li>)}</ol><p className="source-line">{t.officialSite}</p></Section>
    <Section id="iphone" number="03" title={t.sections[2]}><div className="flow">{t.flow}</div><ol>{t.iphoneSteps.map((x, i) => <li key={i}><span>{x}</span></li>)}</ol><h3>{t.trustTitle}</h3><p>{t.trustText}</p><h3>{t.devTitle}</h3><p>{t.devText}</p><ol>{t.devSteps.map(x => <li key={x}><span>{x}</span></li>)}</ol></Section>
    <Section id="source" number="04" title={t.sections[3]}><p>{t.sourceIntro}</p><CopySource lang={lang} /><ol>{t.sourceSteps.map((x, i) => <li key={i}><span>{x}</span></li>)}</ol><Note warning><strong>{t.important}</strong> {t.sourceWarning}</Note></Section>
    <Section id="refresh" number="05" title={t.sections[4]}><p>{t.refreshText}</p><div className="refresh-requirements"><p>{t.refreshLabel}</p><ul>{t.refreshItems.map(x => <li key={x}>{x}</li>)}</ul></div><p>{t.refreshEnd}</p></Section>
    <Section id="xcode" number="06" title={t.sections[5]}><p>{t.pairingIntro}</p><ol>{t.pairingSteps.map((x, i) => <li key={i}><span>{x}</span></li>)}</ol><Note>{t.noAltStore}</Note></Section>
    <Section id="ipa" number="07" title={t.sections[6]}><p>{t.releaseIntro}</p><div className="download"><div><span>{t.forAppleTv}</span><code>Fusion-tvos-unsigned.ipa</code></div><a href="https://github.com/yodaluca23/Fusion-AltStore/releases" target="_blank" rel="noreferrer">{t.download}</a></div><Note warning>{t.wrongIpa}</Note></Section>
    <Section id="sideload" number="08" title={t.sections[7]}><ol>{t.sideloadSteps.map((x, i) => <li key={i}><span>{x}</span></li>)}</ol></Section>
    <Section id="tv-refresh" number="09" title={t.sections[8]}><p>{t.sevenTv}</p><p><strong>{t.noAuto}</strong></p><p>{t.repeat}</p><div className="flow compact">AltServer → Option (⌥) → Sideload .ipa… → Fusion-tvos-unsigned.ipa → Apple TV</div><p>{t.repeatEnd}</p></Section>
    <Section id="order" number="10" title={t.sections[9]}><div className="timeline">{t.orderItems.map(([device, action], i) => <div className="timeline-row" key={action}><b>{String(i + 1).padStart(2, "0")}</b><span className="device">{device}</span><span>{action}</span></div>)}</div></Section>
    <Section id="trouble" number="11" title={t.sections[10]}><div className="trouble-grid">{t.trouble.map(item => <div key={item.title}><h3>{item.title}</h3>{"text" in item && item.text ? <p>{item.text}</p> : null}<ul className="trouble-list">{item.items.map(x => <li key={x}>{x}</li>)}</ul></div>)}</div></Section>
    <footer><div className="section-kicker">12 · {t.sourcesTitle.toUpperCase()}</div><h2>{t.sourcesTitle}</h2><ul>{t.sourceLinks.map((label, i) => <li key={label}><a href={links[i]} target="_blank" rel="noreferrer">{label} ↗</a></li>)}</ul><p><a href="https://github.com/berot3/ios-tvos-sideloading-guides/blob/master/guides/fusion/SOURCES.md">{verificationLabels[lang]} ↗</a></p><p className="small">{t.reviewed}</p><a className="back-to-top" href="#top">{t.backToTop}</a></footer>
  </main>;
}
